### ISSUE TITLE
Git-hg Mirror suitable?

### ISSUE THREAD

**Issue by Piedone** [clach04/bitbucket_tools#1]
We've been running this service for a while: https://githgmirror.com/. It can keep a git and hg repo (or two hg or two git repos) in sync in one direction or bidirectionally. It's also open source and you can run it yourself too. Only deals with code, so no wiki or issues.

Do you think Git-hg Mirror would be a suitable addition to this collection?

**Comment by clach04** [comment]
@Piedone thanks!
https://github.com/clach04/bitbucket_tools/commit/46c1872943acf6a0dd4d5beacd40687252a61890

**Comment by Piedone** [comment]
Thank you!
