### ISSUE TITLE
Translate commit hashes with rerefcommit

### ISSUE THREAD

**Issue by 3dik** [clach04/bitbucket_tools#3]
Maybe my tool [rerefcommitjson](https://git.sr.ht/~edik/rerefcommitjson) is also be a candidate for this document. It allows you to convert all commit hashes in a [Bitbucket issue JSON dump](https://confluence.atlassian.com/bitbucket/export-or-import-issue-data-330797432.html) from hg to git. See the [example section](https://git.sr.ht/~edik/rerefcommitjson#example-ii) for details and usage warnings.

Philip Starkey's [bitbucket-hg-exporter](https://github.com/philipstarkey/bitbucket-hg-exporter/) can also translate hashes, but [only if they are marked up](https://github.com/philipstarkey/bitbucket-hg-exporter/blob/bb89520c68da63feb9140987d5150d442fdb4283/bitbucket_hg_exporter/hg2git.py#L83). rerefcommitjson, however, is able to translate [markup-less hashes](https://confluence.atlassian.com/bitbucket/mark-up-comments-305037452.html#Markupcomments-Changeset) too.

**Comment by clach04** [comment]
@3dik, I copy/pasted your note. Thanks for making it so easy for me to add a reference :)
