### ISSUE TITLE
Maybe mention foss.heptapod.net

### ISSUE THREAD

**Issue by talljosh** [clach04/bitbucket_tools#4]
Your repo is likely to be viewed by people like me who are looking for mercurial hosting or a pain-free way of converting to git. It might be worth mentioning this:

[Heptapod](https://heptapod.net/) is a friendly fork of GitLab that supports mercurial. They offer free hosting for Open Source projects within reason, and they say that they'll offer commercial hosting for non-open-source projects soon. For the announcement about hosting, see [this blog post](https://heptapod.net/a-public-heptapod-for-free-and-open-source-software.html).

**Comment by clach04** [comment]
Thanks for the info, I used your text as-is :)
